# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

gems: [jekyll-paginate]

# Site settings
title: Blog
email: hello@awwapps.com
description: Blog of indie app collective Aww Apps. Insights and struggles about building context aware about iOS apps.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: awwapps
paginate: 3

# Build settings
markdown: kramdown
